### ISSUE TITLE
image naming convention not properly adopted in kustomization.yml

### ISSUE THREAD

**Issue by mkretz** [swisscom/korp#21]
Running `korp scan . -r eas-docker-local.artifactory.swisscom.com` on a container spec

```yaml
      containers:
      - name: splunk-defaults
        image: nginx
        ports:
        - containerPort: 80
```
produces the following kustomization.yml
```yaml
kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
images:
- name: nginx
  newName: eas-docker-local.artifactory.swisscom.com/nginx
```
However, normalizing the image name `nginx` results in the name `docker.io/library/nginx`. Scan should already write the normalized name to kustomization.yml and push should use the normalized name when re-tagging.
